import Head from "next/head";
import Category from "../components/Category";
import Contact from "../components/Contact";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Testimonial from "../components/Testimonial";
import HowWeDo from "../components/HowWeDo";
import SideNav from "../components/SideNav";

export default function Home() {
  return (
    
        <div className="home">
          <Head>
            <title>Aritstry</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <SideNav />
          <Header />
          <HowWeDo />
          <Category />
          <Testimonial />
          <Contact />
          <Footer/>
        </div>
      
  );
}
