import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Aritstry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="butler">Hi i am butler</h1>
      <h1 className="gardena">Hi i am Gardena holmes</h1>
      <h1 className="montserrat">Hi i am Montserrat</h1>
    </div>
  );
}
